### ISSUE TITLE
Zoom level에 따른 K값 조정이 필요한가

### ISSUE THREAD

**Issue by kati-kms** [boostcamp-2020/Project17-B-Map#11]
클러스터링에서 최적의 k가 결정되고 뷰에 보여줄때 클러스터 끼리 기준 거리 이하로 떨어져 있을 경우 (예를 들어 겹치는 경우)
두 클러스터를 합친것 처럼 보여준다.

예를들어 k가 5일때 최적인데, 어느 두 클러스터가 겹치는 경우
뷰에서는 그 두 클러스터를 합쳐 4개의 클러스터로 보여준다.

**Comment by chojl1125** [comment]
- 클러스터가 인접해있을 경우 하나의 클러스터로 합치도록 구현. (화면상 두 클러스터 간 CGPoint distance 계산)
- 더 이상 가까워 지지 않을때까지 반복
