### ISSUE TITLE
Animation 버그 수정

### ISSUE THREAD

**Issue by SeokBA** [boostcamp-2020/Project17-B-Map#54]
- 빠르게 움직일 시, 이전 마커가 화면에 남아있는 문제

**Comment by jaekyoungshin** [comment]
> * 빠르게 움직일 시, 이전 마커가 화면에 남아있는 문제

잔상이 남아있는 형태가 된다면? animation은 실제로 어떤 메카니즘으로 지원하는 걸까요?
UI는 일반적으로 화면을 전체적으로 업데이트한다면 잔상은 생길수 없잖아요?

**Comment by SeokBA** [comment]
> > * 빠르게 움직일 시, 이전 마커가 화면에 남아있는 문제
> 
> 잔상이 남아있는 형태가 된다면? animation은 실제로 어떤 메카니즘으로 지원하는 걸까요?
> UI는 일반적으로 화면을 전체적으로 업데이트한다면 잔상은 생길수 없잖아요?

현재 맵뷰의 마커와 마커 애니메이션 전용 뷰가 따로 움직이는 방식으로 구현되어있습니다.
따라서 애니메이션 후에 마커가 mapView로 오버레이 되도록 구현했는데 여러 번 빠르게 호출되다 보면 completion이 여러 번 일어나게 되어 공유 자원에 중복 접근을 하면서 화면에 오버레이된 이전 마커(UIView가 아닌, NMFMarker)가 지워지지 않고 남아있게 되어 생기는 문제로 판단했습니다.

**Comment by jaekyoungshin** [comment]
> > > * 빠르게 움직일 시, 이전 마커가 화면에 남아있는 문제
> > 
> > 
> > 잔상이 남아있는 형태가 된다면? animation은 실제로 어떤 메카니즘으로 지원하는 걸까요?
> > UI는 일반적으로 화면을 전체적으로 업데이트한다면 잔상은 생길수 없잖아요?
> 
> 현재 맵뷰의 마커와 마커 애니메이션 전용 뷰가 따로 움직이는 방식으로 구현되어있습니다.
> 따라서 애니메이션 후에 마커가 mapView로 오버레이 되도록 구현했는데 여러 번 빠르게 호출되다 보면 completion이 여러 번 일어나게 되어 공유 자원에 중복 접근을 하면서 화면에 오버레이된 이전 마커(UIView가 아닌, NMFMarker)가 지워지지 않고 남아있게 되어 생기는 문제로 판단했습니다.

실제로 그럴까요? 좀 더 깊이 들어가서 이전 마커가 지워지지 않는다고 했는데 실제로 그렇다면 우리가 하는 모든 작업은 partial update형태로 동작하게 되는건가요?
