### ISSUE TITLE
CoreData Add 구조 변경

### ISSUE THREAD

**Issue by wogus3602** [boostcamp-2020/Project17-B-Map#56]
- 모든 Add가 끝날시 한번에 save하는 로직으로 변경하기

**Comment by jaekyoungshin** [comment]
> * 모든 Add가 끝날시 한번에 save하는 로직으로 변경하기

이렇게 로직을 만들기로 결정하신 이유가 있으신가요? core data를 쓰는 관점에서 궁금해지네요.

**Comment by KYHyeon** [comment]
@jaekyoungshin [링크](https://developer.apple.com/library/archive/documentation/Cocoa/Conceptual/CoreData/Concurrency.html#//apple_ref/doc/uid/TP40001075-CH24-SW1) 를 참고하여 jsonArray에서 객체를 하나씩 생성한 후 한번에 save를 하는 것을 봤습니다.
실제로 적용해 보니 add를 하나씩 하고 save를 할 때 보다 한번에 save를 했을 때 속도적인 측면에서 크게 차이가 나는 것을 볼 수 있었습니다.
저희 생각으로는 private 컨텍스트에서 부모 컨텍스트로 이동할 때 오버헤드가 발생해서 그런 것 같습니다.
